[package]
name = "fs"
version = "0.2.1"
edition = "2021"

description = "Tui based basic file explorer"
repository = "https://github.com/devendra-official/FileScout"
readme = "README.md"

[dependencies]
aes-gcm = "0.10.3"
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
